FROM almalinux:9
ENV course_name="DevOps"\
    course_date="2023-05-05"\
    course_time="10:00"
ADD https://raw.githubusercontent.com/daws-86s/notes/refs/heads/main/session-53.txt /tmp/session-53.txt
ADD sample-2.tar /tmp/
CMD [ "sleep","1000" ]